[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-ancestors https://www.candourfunerals.com.au https://candourfunerals.com.au *.webflow.io;"
